In [7]:
import pandas as pd

In [10]:
data = pd.read_csv('results/semantic_results.csv')
#data.head(1)
data

,query,item_title,review,rating,score
0,nintendo switch screen protector,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.7993
1,gaming headset with microphone,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.9859
2,xbox 360 wireless controller,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.9102
3,fifa 16 game for playstation,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.3834
4,playstation games for sports lovers,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.0941
5,competitive multiplayer game for large groups,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.4858
6,comfortable headset for long gaming sessions,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.9017
7,ps4 controller with good battery life,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.7388
8,best wireless gaming headset for ps5 with good microphone under $100,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.7676
9,good single player story game for a beginner who just got their first playstation under $50,the dark pictures house of ashes playstation 5,the dark pictures house of ashes playstation 5 house of ashes is the third game in the the dark pictures anthology series standalone cinematic branching horror games where the decisions you make in,4.6,1.1448

In [6]:
pd.set_option('display.max_colwidth', None)
data = pd.read_csv('results/semantic_results.csv')
data.head(1)

,query,item_title,review,rating,score
0,nintendo switch screen protector,evoretro screen protector compatible for nintendo switch lite ultra clear heavy duty tempered glass protection kit with high accuracy response and premium protection 2pack,evoretro screen protector compatible for nintendo switch lite ultra clear heavy duty tempered glass protection kit with high accuracy response and premium protection 2pack our premium nintendo,4.6,0.396